# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaSdk.Api.Default do
  @moduledoc """
  API calls for all endpoints tagged `Default`.
  """

  alias RasaSdk.Connection
  import RasaSdk.RequestBuilder


  @doc """
  Core request to execute a custom action
  Rasa Core sends a request to the action server to execute a certain custom action. As a response to the action call from Core, you can modify the tracker, e.g. by setting slots and send responses back to the user.

  ## Parameters

  - connection (RasaSdk.Connection): Connection to server
  - inline_object (InlineObject): 
  - opts (KeywordList): [optional] Optional parameters
  ## Returns

  {:ok, %RasaSdk.Model.InlineResponse200{}} on success
  {:error, info} on failure
  """
  @spec call_action(Tesla.Env.client, RasaSdk.Model.InlineObject.t, keyword()) :: {:ok, RasaSdk.Model.InlineResponse200.t} | {:error, Tesla.Env.t}
  def call_action(connection, inline_object, _opts \\ []) do
    %{}
    |> method(:post)
    |> url("/")
    |> add_param(:body, :body, inline_object)
    |> Enum.into([])
    |> (&Connection.request(connection, &1)).()
    |> evaluate_response([
      { 200, %RasaSdk.Model.InlineResponse200{}},
      { 400, %RasaSdk.Model.InlineResponse400{}},
      { 500, false}
    ])
  end
end
