# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaSdk.Model.ButtonResponse do
  @moduledoc """
  Text with buttons which should be sent to the user.
  """
  alias RasaSdk.Model.Button

  @derive [Poison.Encoder]
  defstruct [
    :text,
    :buttons
  ]

  @type t :: %__MODULE__{
    text: String.t | nil,
    buttons: [Button] | nil
  }
end

defimpl Poison.Decoder, for: RasaSdk.Model.ButtonResponse do
  import RasaSdk.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:buttons, :list, RasaSdk.Model.Button, options)
  end
end

