# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaSdk.Model.Intent do
  @moduledoc """
  Intent of the text
  """

  @derive [Poison.Encoder]
  defstruct [
    :confidence,
    :name
  ]

  @type t :: %__MODULE__{
    confidence: float(),
    name: String.t
  }
end

defimpl Poison.Decoder, for: RasaSdk.Model.Intent do
  def decode(value, _options) do
    value
  end
end

