# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule RasaSdk.Model.ResponseOk do
  @moduledoc """
  Action was executed succesfully.
  """
  alias RasaSdk.Model.Event
  alias RasaSdk.Model.Response

  @derive [Poison.Encoder]
  defstruct [
    :events,
    :responses
  ]

  @type t :: %__MODULE__{
    events: [Event] | nil,
    responses: [Response] | nil
  }
end

defimpl Poison.Decoder, for: RasaSdk.Model.ResponseOk do
  import RasaSdk.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:events, :list, RasaSdk.Model.Event, options)
    |> deserialize(:responses, :list, RasaSdk.Model.Response, options)
  end
end

